### ISSUE TITLE
Clever install clever-users issue

### ISSUE THREAD

**Issue by MauritzKruger** [CleverStack/clever-users#1]
Running install command for clever-users results in following error(s):

```
clever install clever-users
Attempting to install clever-users...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-users...
  ├── Installing NPM modules for clever-users...
✔    Successfully installed clever-users...
  ├── Installing bundledDependencies...
  ├── Installing bundled dependencies within /vagrant/cs-latest/backend/modules/clever-users
Possibly unhandled TypeError: Object Error: Cannot find module 'config' has no method 'match'
    at /usr/lib/node_modules/cleverstack-cli/lib/util/grunt.js:73:26
From previous event:
    at new Promise (/usr/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at exports.findGruntFile (/usr/lib/node_modules/cleverstack-cli/lib/util/grunt.js:91:12)
    at /usr/lib/node_modules/cleverstack-cli/lib/util/grunt.js:67:9
From previous event:
    at new Promise (/usr/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at exports.readTasks (/usr/lib/node_modules/cleverstack-cli/lib/util/grunt.js:62:12)
    at /usr/lib/node_modules/cleverstack-cli/lib/util/grunt.js:182:9
From previous event:
    at new Promise (/usr/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at Object.exports.runTasks (/usr/lib/node_modules/cleverstack-cli/lib/util/grunt.js:181:12)
    at /usr/lib/node_modules/cleverstack-cli/lib/install.js:131:46
    at iterate (/usr/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/usr/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:165:9)
    at /usr/lib/node_modules/cleverstack-cli/lib/install.js:127:39
From previous event:
    at new Promise (/usr/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at Object.exports.addToMainBundleDeps (/usr/lib/node_modules/cleverstack-cli/lib/util/dependencies.js:92:12)
    at /usr/lib/node_modules/cleverstack-cli/lib/install.js:124:30
    at done (/usr/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:135:19)
    at /usr/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:32:16
    at /usr/lib/node_modules/cleverstack-cli/lib/install.js:115:33
From previous event:
    at new Promise (/usr/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at Object.exports.installBundleDeps (/usr/lib/node_modules/cleverstack-cli/lib/util/dependencies.js:17:12)
    at /usr/lib/node_modules/cleverstack-cli/lib/install.js:113:30
    at /usr/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/usr/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:124:9)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/cleverstack-cli/lib/install.js:109:23)
```

**Comment by pilsy** [comment]
I have published new versions of the node-seed and this module (along with others)... if that doesn't fix it what version of cleverstack-cli are you using? and also what version of node-seed?

**Comment by marco-gallinari** [comment]
@pilsy, i'm experiencing the same issue.

cleverstack-cli is version 1.1.6, app is a new init with clever-orm installed.

```
⇒  clever install clever-users    
Attempting to install clever-users...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-users...
  ├── Installing NPM modules for clever-users...
✔    Successfully installed clever-users...
  ├── Installing bundledDependencies...
Possibly unhandled TypeError: Object Error: Cannot find module 'config' has no method 'match'
    at /usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:73:26
From previous event:
    at new Promise (/usr/local/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at exports.findGruntFile (/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:91:12)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:67:9
From previous event:
    at new Promise (/usr/local/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at exports.readTasks (/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:62:12)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:182:9
From previous event:
    at new Promise (/usr/local/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at Object.exports.runTasks (/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:181:12)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:131:46
    at iterate (/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:165:9)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:127:39
From previous event:
    at new Promise (/usr/local/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at Object.exports.addToMainBundleDeps (/usr/local/lib/node_modules/cleverstack-cli/lib/util/dependencies.js:92:12)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:124:30
    at done (/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:135:19)
    at /usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:115:33
From previous event:
    at new Promise (/usr/local/lib/node_modules/cleverstack-cli/node_modules/bluebird/js/main/promise.js:84:37)
    at Object.exports.installBundleDeps (/usr/local/lib/node_modules/cleverstack-cli/lib/util/dependencies.js:17:12)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:113:30
    at /usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:124:9)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:109:23)
```

**Comment by marco-gallinari** [comment]
if this could be of any help, error changed to:

```
⇒  clever install clever-users
Attempting to install clever-users...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-users...
  ├── Installing NPM modules for clever-users...
✔    Successfully installed clever-users...
Unhandled rejection TypeError: undefined is not a function
    at /usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:94:17
    at process._tickCallback (node.js:355:11)
From previous event:
    at /usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:93:13
From previous event:
    at exports.readTasks (/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:83:10)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:182:5
From previous event:
    at Object.exports.runTasks (/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:181:10)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:89:16
    at Array.forEach (native)
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:85:13
    at process._tickCallback (node.js:355:11)
From previous event:
    at /usr/local/lib/node_modules/cleverstack-cli/lib/install.js:82:8
From previous event:
    at Object.exports.run (/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/cleverstack-cli/bin/clever-install:38:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by pilsy** [comment]
@marco-gallinari @MauritzKruger - can you guys update the CLI to 1.2.2 and try again? (the node-seed 1.2.0 and above requires the latest CLI)

`npm install cleverstack-cli -g`

**Comment by pilsy** [comment]
This should be resolved now, in https://github.com/CleverStack/cleverstack-cli/issues/65.

Please re-open the issue if it is not fixed for you
